### ISSUE TITLE
Object rest spread

### ISSUE THREAD

**Issue by chaitanyapotti** [MetaMask/eth-json-rpc-infura#11]
https://github.com/MetaMask/eth-json-rpc-infura/blob/master/src/index.js#L117

Several tool chains don't transpile node_modules by default.
Please use extend and not `...`

This would allow people to use the library directly in edge browser.
Note: Edge doesn't support rest spread operator

**Comment by kumavis** [comment]
@chaitanyapotti thanks, shipping this
